"""teste

Revision ID: 3d7590e78390
Revises: 
Create Date: 2022-07-11 10:28:59.997462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7590e78390'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_model_id'), 'example_model', ['id'], unique=False)
    op.create_index(op.f('ix_example_model_name'), 'example_model', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_model_name'), table_name='example_model')
    op.drop_index(op.f('ix_example_model_id'), table_name='example_model')
    op.drop_table('example_model')
    # ### end Alembic commands ###
